### ISSUE TITLE
Clarification regarding licenses

### ISSUE THREAD

**Issue by daniel-evers** [scottjehl/Respond#379]
The repository itself has only a MIT license file in its root directory. If you take a look at the source files, it appears to be a dual MIT/BSD license.

Regarding this, I have some questions for clarification.

- Is it possible to update the corresponding license file in the root directory to immediately recognize the dual license?
- Which BSD license is used exactly (1, 2, 3, 4, ...)?
- It is possible to use [SPDX identifiers](https://spdx.org/licenses)?
- Is it beneficial to create a pull request (I ask because this project doesn't seem to be maintained)?

**Comment by moritzuehling** [comment]
Hi @daniel-evers, just stopping by, not affiliated with the project. 

I'm not sure if you can expect an answer. This project unlocks a feature for Internet Explorer 6-8, mostly. IE8 went [end of life on Oct 13, 2020](https://learn.microsoft.com/en-us/lifecycle/products/internet-explorer-8), and basically all still-supported browsers support the feature this library is trying to replicate.

This project has, even in the enterprise world, no more use. I would suggest instead trying to remove the dependency, instead of trying to get any licensing issue sorted out. I would be surprised if your company still uses a Browser this old, but it's been a while since I worked for them :)

So yeah, trying to get the dependency removed is probably a more productive use of your time!

**Comment by daniel-evers** [comment]
Hi @moritzuehling, thank you very much for your feedback. Yes, you are exactly right. This project should no longer be needed in practice. I would therefore consider the ticket to be closed.
